#!/bin/bash
# git pull --quiet
# python -m manga_translator local --use-gpu -v -i 'G:\manga\F' --config-file 'E:\MangaTranslator\manga-image-translator\examples\config-example.toml'
# python -m manga_translator local --use-gpu -v -i 'G:\manga\G' --config-file 'E:\MangaTranslator\manga-image-translator\examples\config-example.toml'
# python -m manga_translator local --use-gpu -v -i 'G:\manga\H' --config-file 'E:\MangaTranslator\manga-image-translator\examples\config-example.toml'
# python -m manga_translator local --use-gpu -v -i 'G:\manga\I' --config-file 'E:\MangaTranslator\manga-image-translator\examples\config-example.toml'
# python -m manga_translator local --use-gpu -v -i 'G:\manga\J' --config-file 'E:\MangaTranslator\manga-image-translator\examples\config-example.toml'
# python -m manga_translator local --use-gpu -v -i 'G:\manga\K' --config-file 'E:\MangaTranslator\manga-image-translator\examples\config-example.toml'
# python -m manga_translator local --use-gpu -v -i 'G:\manga\L1' --config-file 'E:\MangaTranslator\manga-image-translator\examples\config-example.toml'
# python -m manga_translator local --use-gpu -v -i 'G:\manga\L2' --config-file 'E:\MangaTranslator\manga-image-translator\examples\config-example.toml'
# python -m manga_translator local --use-gpu -v -i 'G:\manga\L3' --config-file 'E:\MangaTranslator\manga-image-translator\examples\config-example.toml'
# python -m manga_translator local --use-gpu -v -i 'G:\manga\A' --config-file 'E:\MangaTranslator\manga-image-translator\examples\config-example.toml'
python webptopdf.py  'G:\manga\translated\Sentai1'  'G:\manga\translated\Sentai2'  'G:\manga\translated\Sentai3'  'G:\manga\translated\Sentai4'  'G:\manga\translated\Sentai5'  'G:\manga\translated\Sentai6'  'G:\manga\translated\Sentai7'  'G:\manga\translated\Sentai8'  'G:\manga\translated\Sentai9'  'G:\manga\translated\Sentai10'  'G:\manga\translated\Sentai11'  'G:\manga\translated\Sentai12'  'G:\manga\translated\Sentai13'  'G:\manga\translated\SentaiWorld.pdf'

# python webptopdf.py 'G:\manga\translated\A1' 'G:\manga\translated\A1.pdf'
# python webptopdf.py 'G:\manga\translated\A2' 'G:\manga\translated\A2.pdf'
# python webptopdf.py 'G:\manga\translated\A-translated' 'G:\manga\translated\A.pdf'
# python webptopdf.py 'G:\manga\translated\B-translated' 'G:\manga\translated\B.pdf'
# python webptopdf.py 'G:\manga\translated\C-translated' 'G:\manga\translated\C.pdf'
# python webptopdf.py 'G:\manga\translated\D-translated' 'G:\manga\translated\D.pdf'
# python webptopdf.py 'G:\manga\translated\E-translated' 'G:\manga\translated\E.pdf'
# python webptopdf.py 'G:\manga\translated\F-translated' 'G:\manga\translated\F.pdf'
# python webptopdf.py 'G:\manga\translated\G-translated' 'G:\manga\translated\G.pdf'
# python webptopdf.py 'G:\manga\H-translated' 'G:\manga\translated\H.pdf'
# python webptopdf.py 'G:\manga\J-translated' 'G:\manga\translated\J.pdf'
# python webptopdf.py 'G:\manga\K-translated' 'G:\manga\translated\K.pdf'
# python webptopdf.py 'G:\manga\L4-translated' 'G:\manga\L3-translated' 'G:\manga\L2-translated' 'G:\manga\L1-translated' 'G:\manga\translated\L.pdf'